// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4xyYnEaOyimjd0Xq5fa2f2P18oDBIfng',
    appId:
        '1:385551792398:web:595ad848612a4aa26f3f5f', // You'll need to add a web app in Firebase Console
    messagingSenderId: '385551792398',
    projectId: 'ahlanfeekum-de666',
    authDomain: 'ahlanfeekum-de666.firebaseapp.com',
    storageBucket: 'ahlanfeekum-de666.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4xyYnEaOyimjd0Xq5fa2f2P18oDBIfng',
    appId: '1:385551792398:android:4f2fe2132a8069086f3f5f',
    messagingSenderId: '385551792398',
    projectId: 'ahlanfeekum-de666',
    storageBucket: 'ahlanfeekum-de666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4xyYnEaOyimjd0Xq5fa2f2P18oDBIfng',
    appId:
        '1:385551792398:ios:YOUR_IOS_APP_ID', // You'll need to add an iOS app in Firebase Console
    messagingSenderId: '385551792398',
    projectId: 'ahlanfeekum-de666',
    storageBucket: 'ahlanfeekum-de666.firebasestorage.app',
    iosBundleId: 'com.example.ahlanfeekum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4xyYnEaOyimjd0Xq5fa2f2P18oDBIfng',
    appId: '1:385551792398:ios:YOUR_IOS_APP_ID', // Reusing iOS config for macOS
    messagingSenderId: '385551792398',
    projectId: 'ahlanfeekum-de666',
    storageBucket: 'ahlanfeekum-de666.firebasestorage.app',
    iosBundleId: 'com.example.ahlanfeekum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4xyYnEaOyimjd0Xq5fa2f2P18oDBIfng',
    appId:
        '1:385551792398:web:595ad848612a4aa26f3f5f', // Reusing web config for Windows
    messagingSenderId: '385551792398',
    projectId: 'ahlanfeekum-de666',
    authDomain: 'ahlanfeekum-de666.firebaseapp.com',
    storageBucket: 'ahlanfeekum-de666.firebasestorage.app',
  );
}
